import { GoogleGenAI } from "@google/genai";

export const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export const REWARD_CONFIG = {
  TARGET_REWARD: 3210000,
  FARD: {
    FAJR: { base: 2000, jamaat: 500, masjid: 300, onTime: 200, khushu: 300, sunnahBefore: 200, sunnahAfter: 200 },
    ZOHR: { base: 1000, jamaat: 500, masjid: 300, onTime: 200, khushu: 300, sunnahBefore: 200, sunnahAfter: 200 },
    ASR: { base: 1000, jamaat: 500, masjid: 300, onTime: 200, khushu: 300, sunnahBefore: 200, sunnahAfter: 200 },
    MAGHRIB: { base: 1000, jamaat: 500, masjid: 300, onTime: 200, khushu: 300, sunnahBefore: 200, sunnahAfter: 200 },
    ISHA: { base: 1500, jamaat: 500, masjid: 300, onTime: 200, khushu: 300, sunnahBefore: 200, sunnahAfter: 200 },
  },
  NAFL: {
    TAHAJJUD: { base: 100, rakats2: 50, rakats4: 100, withDua: 50, streak: 50 },
    ISHRAQ: { base: 10, rakats2: 5, rakats4: 10, withDua: 5, streak: 5 },
    CHASHT: { base: 10, rakats2: 5, rakats4: 10, withDua: 5, streak: 5 },
    AWWABEEN: { base: 10, rakats2: 5, rakats4: 10, withDua: 5, streak: 5 },
  },
  TILAWAT: {
    page1: 20,
    page2: 40,
    page5: 100,
    page10: 200,
    juz1: 300,
    tajweed: 50,
    understanding: 100,
    memorization: 200,
    revision: 100,
  },
  MAMULAT: {
    DUA: { morning: 20, evening: 20, afterSalah: 10, personal: 30 },
    ZIKR: { subhanallah100: 20, alhamdulillah100: 20, allahuakbar100: 20, astaghfirullah100: 30, durood100: 40, ayatulKursi: 20, surahIkhlas3: 30 },
  },
  GOOD_DEEDS: {
    smiling: 5,
    helpingParents: 100,
    smallCharity: 100,
    largeCharity: 500,
    teachingKnowledge: 200,
    visitingSick: 100,
    feedingSomeone: 200,
    removingHarm: 50,
    forgivingSomeone: 300,
    seekingKnowledge: 150,
    dawahConversation: 250,
    volunteering: 200,
    communityService: 300,
    supportingOrphans: 400,
  }
};

export const TRANSLATIONS = {
  en: {
    app_name: "IbadahMate",
    dashboard: "Dashboard",
    salah: "Salah",
    nafl: "Nafl",
    tilawat: "Tilawat",
    mamulat: "Mamulat",
    good_deeds: "Good Deeds",
    stats: "Statistics",
    fajr: "Fajr",
    zohr: "Zohr",
    asr: "Asr",
    maghrib: "Maghrib",
    isha: "Isha",
    tahajjud: "Tahajjud",
    ishraq: "Ishraq",
    chasht: "Chasht",
    awwabeen: "Awwabeen",
    dua: "Dua",
    zikr: "Zikr",
    total_reward: "Total Reward",
    target: "Target",
    progress: "Progress",
    milestone_0: "Keep Going 🌱",
    milestone_25: "Growing Strong 🌿",
    milestone_50: "Elite Discipline 🌙",
    milestone_75: "Spiritual Excellence 🔥",
  },
  ar: {
    app_name: "IbadahMate",
    dashboard: "لوحة القيادة",
    salah: "الصلاة (Ṣalāt)",
    nafl: "النفل (Nafl)",
    tilawat: "التلاوة (Tilāwat)",
    mamulat: "المعمولات (Mamūlāt)",
    good_deeds: "الأعمال الصالحة",
    stats: "الإحصائيات",
    fajr: "الفجر (Ṣalāt al-Fajr)",
    zohr: "الظهر (Ṣalāt aẓ-Ẓuhr)",
    asr: "العصر (Ṣalāt al-ʿAṣr)",
    maghrib: "المغرب (Ṣalāt al-Maghrib)",
    isha: "العشاء (Ṣalāt al-ʿIshāʾ)",
    tahajjud: "تهجد (Tahajjud)",
    ishraq: "إشراق (Ishraq)",
    chasht: "ضحى (Chasht)",
    awwabeen: "أوابين (Awwabeen)",
    dua: "دعاء (Du‘ā)",
    zikr: "ذكر (Dhikr)",
    total_reward: "إجمالي الثواب",
    target: "الهدف",
    progress: "التقدم",
    milestone_0: "استمر 🌱",
    milestone_25: "تنمو بقوة 🌿",
    milestone_50: "انضباط النخبة 🌙",
    milestone_75: "التميز الروحي 🔥",
  }
};
